/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'title' : string,
  'externalBlob' : ExternalBlob,
  'fileName' : string,
  'filePath' : string,
  'fileSize' : bigint,
  'fileType' : { 'doc' : null } |
    { 'pdf' : null },
  'author' : string,
  'submissionDate' : Time,
}
export interface ArticlePreview {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'author' : string,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'blob' : [] | [ExternalBlob],
  'authorName' : string,
  'shortSummary' : string,
  'imageUrl' : [] | [string],
  'publicationDate' : Time,
}
export interface EditorialMember {
  'id' : bigint,
  'blob' : [] | [ExternalBlob],
  'name' : string,
  'createdAt' : Time,
  'role' : string,
  'isEditorialBoardAuthor' : boolean,
  'email' : string,
  'expertise' : string,
  'profilePictureUrl' : string,
  'isEditorInChief' : boolean,
  'phone' : string,
  'isReviewerBoardMember' : boolean,
  'qualification' : string,
}
export type ExternalBlob = Uint8Array;
export interface HomePageArticle {
  'title' : string,
  'description' : string,
  'author' : string,
  'submissionDate' : Time,
}
export interface HomePageMagazine {
  'id' : bigint,
  'title' : string,
  'publishedDate' : Time,
  'description' : string,
  'imageUrl' : string,
  'issue' : string,
}
export interface Journal {
  'id' : bigint,
  'month' : bigint,
  'title' : string,
  'blob' : ExternalBlob,
  'year' : bigint,
  'description' : string,
  'fileSize' : bigint,
  'fileType' : { 'pdf' : null },
  'filename' : string,
  'isArchive' : boolean,
  'isCurrent' : boolean,
  'uploadDate' : Time,
}
export interface Magazine {
  'id' : bigint,
  'title' : string,
  'publishedDate' : Time,
  'description' : string,
  'imageUrl' : string,
  'issue' : string,
}
export interface News {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'summary' : string,
}
export interface ProfileInput {
  'occupation' : string,
  'name' : string,
  'isUnlimited' : boolean,
  'email' : string,
  'phone' : string,
  'isInstitute' : boolean,
  'qualification' : string,
}
export interface ProfileOutput {
  'occupation' : string,
  'name' : string,
  'isUnlimited' : boolean,
  'email' : string,
  'phone' : string,
  'isInstitute' : boolean,
  'activeSubscriptions' : [] | [Array<Subscription>],
  'qualification' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'endDate' : Time,
  'planId' : string,
  'isUnlimited' : boolean,
  'isActive' : boolean,
  'remainingArticles' : bigint,
  'isInstitute' : boolean,
  'startDate' : Time,
}
export interface SubscriptionPlan {
  'id' : string,
  'name' : string,
  'durationMonths' : bigint,
  'isUnlimited' : boolean,
  'maxArticles' : bigint,
  'price' : bigint,
  'isInstitute' : boolean,
}
export interface TermsPlaceholders {
  'websiteName' : string,
  'companyEmail' : string,
  'lastUpdateDate' : string,
  'addressCity' : string,
  'companyName' : string,
  'companyAddress' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'occupation' : string,
  'name' : string,
  'isUnlimited' : boolean,
  'email' : string,
  'phone' : string,
  'isInstitute' : boolean,
  'qualification' : string,
}
export interface UserReview {
  'id' : bigint,
  'name' : string,
  'photoUrl' : [] | [string],
  'feedback' : string,
  'rating' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisitorCounter {
  'averageSessionDuration' : bigint,
  'activeSessions' : [] | [bigint],
  'totalSessions' : bigint,
  'pageViews' : bigint,
  'uniqueVisitors' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogPost' : ActorMethod<
    [string, string, string, [] | [string], Time, [] | [ExternalBlob], string],
    undefined
  >,
  'addEditorialMember' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      boolean,
      string,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'addNews' : ActorMethod<[string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[string], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createFeaturedHomePageMagazine' : ActorMethod<
    [string, string, string, string, Time],
    undefined
  >,
  'createHomePageArticle' : ActorMethod<
    [string, string, string, Time],
    undefined
  >,
  'createHomePageMagazine' : ActorMethod<
    [string, string, string, string, Time],
    undefined
  >,
  'createMagazine' : ActorMethod<
    [string, string, string, string, Time],
    undefined
  >,
  'createSubscription' : ActorMethod<[string, Time], undefined>,
  'createUserReview' : ActorMethod<
    [string, [] | [string], bigint, string],
    undefined
  >,
  'deleteArticle' : ActorMethod<[string], undefined>,
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  'deleteEditorialMember' : ActorMethod<[bigint], undefined>,
  'deleteNews' : ActorMethod<[string], undefined>,
  'getAllArticlePreviews' : ActorMethod<[], Array<ArticlePreview>>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllEditorialMembers' : ActorMethod<[], Array<EditorialMember>>,
  'getAllJournalsByYear' : ActorMethod<[bigint], Array<Journal>>,
  'getAllMagazines' : ActorMethod<[], Array<Magazine>>,
  'getAllNews' : ActorMethod<[], Array<News>>,
  'getAllPendingArticles' : ActorMethod<[], Array<Article>>,
  'getAllUserReviews' : ActorMethod<[], Array<UserReview>>,
  'getArticlePreview' : ActorMethod<[bigint], ArticlePreview>,
  'getBlogPost' : ActorMethod<[bigint], BlogPost>,
  'getBlogPostCount' : ActorMethod<[], bigint>,
  'getBlogPostsPaginated' : ActorMethod<[bigint, bigint], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentJournal' : ActorMethod<[], [] | [Journal]>,
  'getEditorInChiefMembers' : ActorMethod<[], Array<EditorialMember>>,
  'getEditorialBoardMembers' : ActorMethod<[], Array<EditorialMember>>,
  'getFilteredProfilesDTOs' : ActorMethod<
    [boolean, boolean],
    Array<ProfileOutput>
  >,
  'getHomePageArticles' : ActorMethod<[], Array<HomePageArticle>>,
  'getHomePageMagazines' : ActorMethod<[], Array<HomePageMagazine>>,
  'getJournal' : ActorMethod<[bigint], Journal>,
  'getJournalCount' : ActorMethod<[], bigint>,
  'getLatestBlogPosts' : ActorMethod<[bigint], Array<BlogPost>>,
  'getLatestNews' : ActorMethod<[bigint], Array<News>>,
  'getMagazine' : ActorMethod<[bigint], Magazine>,
  'getNews' : ActorMethod<[string], News>,
  'getNewsCount' : ActorMethod<[], bigint>,
  'getPendingArticleCount' : ActorMethod<[], bigint>,
  'getPlanCount' : ActorMethod<[], bigint>,
  'getRemainingArticles' : ActorMethod<[Principal], bigint>,
  'getReviewerBoardMembers' : ActorMethod<[], Array<EditorialMember>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscriptionPlanObject' : ActorMethod<[string], SubscriptionPlan>,
  'getSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getTermsAndConditions' : ActorMethod<[], string>,
  'getTermsPlaceholders' : ActorMethod<[], TermsPlaceholders>,
  'getUserArticles' : ActorMethod<[Principal], Array<Article>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReview' : ActorMethod<[bigint], UserReview>,
  'getUsersByPlan' : ActorMethod<[string], Array<Principal>>,
  'getVisitorCounter' : ActorMethod<[], VisitorCounter>,
  'hasActiveSubscription' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[ProfileInput], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setTermsPlaceholders' : ActorMethod<[TermsPlaceholders], undefined>,
  'submitArticle' : ActorMethod<
    [string, { 'doc' : null } | { 'pdf' : null }, string, bigint, ExternalBlob],
    undefined
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateArticleStatus' : ActorMethod<
    [Principal, string, { 'approved' : null } | { 'rejected' : null }],
    undefined
  >,
  'updateBlogPost' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Time,
      [] | [string],
      [] | [ExternalBlob],
      string,
    ],
    undefined
  >,
  'updateEditorialMember' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      boolean,
      string,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'updateSubscriptionsTimestamp' : ActorMethod<[], undefined>,
  'updateTermsAndConditions' : ActorMethod<[string], undefined>,
  'updateVisitorCounter' : ActorMethod<
    [bigint, bigint, bigint, bigint, [] | [bigint]],
    undefined
  >,
  'uploadJournal' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      string,
      string,
      bigint,
      ExternalBlob,
      boolean,
      boolean,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];