/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface HomePageArticle {
    title: string;
    description: string;
    author: string;
    submissionDate: Time;
}
export interface Subscription {
    endDate: Time;
    planId: string;
    isUnlimited: boolean;
    isActive: boolean;
    remainingArticles: bigint;
    isInstitute: boolean;
    startDate: Time;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface UserReview {
    id: bigint;
    name: string;
    photoUrl?: string;
    feedback: string;
    rating: bigint;
}
export interface EditorialMember {
    id: bigint;
    blob?: ExternalBlob;
    name: string;
    createdAt: Time;
    role: string;
    isEditorialBoardAuthor: boolean;
    email: string;
    expertise: string;
    profilePictureUrl: string;
    isEditorInChief: boolean;
    phone: string;
    isReviewerBoardMember: boolean;
    qualification: string;
}
export interface SubscriptionPlan {
    id: string;
    name: string;
    durationMonths: bigint;
    isUnlimited: boolean;
    maxArticles: bigint;
    price: bigint;
    isInstitute: boolean;
}
export interface HomePageMagazine {
    id: bigint;
    title: string;
    publishedDate: Time;
    description: string;
    imageUrl: string;
    issue: string;
}
export interface ProfileOutput {
    occupation: string;
    name: string;
    isUnlimited: boolean;
    email: string;
    phone: string;
    isInstitute: boolean;
    activeSubscriptions?: Array<Subscription>;
    qualification: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface Article {
    status: Variant_pending_approved_rejected;
    title: string;
    externalBlob: ExternalBlob;
    fileName: string;
    filePath: string;
    fileSize: bigint;
    fileType: Variant_doc_pdf;
    author: string;
    submissionDate: Time;
}
export interface ArticlePreview {
    id: bigint;
    title: string;
    description: string;
    author: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface VisitorCounter {
    averageSessionDuration: bigint;
    activeSessions?: bigint;
    totalSessions: bigint;
    pageViews: bigint;
    uniqueVisitors: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Journal {
    id: bigint;
    month: bigint;
    title: string;
    blob: ExternalBlob;
    year: bigint;
    description: string;
    fileSize: bigint;
    fileType: Variant_pdf;
    filename: string;
    isArchive: boolean;
    isCurrent: boolean;
    uploadDate: Time;
}
export interface News {
    id: string;
    title: string;
    content: string;
    createdAt: Time;
    summary: string;
}
export interface Magazine {
    id: bigint;
    title: string;
    publishedDate: Time;
    description: string;
    imageUrl: string;
    issue: string;
}
export interface ProfileInput {
    occupation: string;
    name: string;
    isUnlimited: boolean;
    email: string;
    phone: string;
    isInstitute: boolean;
    qualification: string;
}
export interface UserProfile {
    occupation: string;
    name: string;
    isUnlimited: boolean;
    email: string;
    phone: string;
    isInstitute: boolean;
    qualification: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_approved_rejected {
    approved = "approved",
    rejected = "rejected"
}
export enum Variant_doc_pdf {
    doc = "doc",
    pdf = "pdf"
}
export enum Variant_pdf {
    pdf = "pdf"
}
export enum Variant_pending_approved_rejected {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addEditorialMember(name: string, qualification: string, role: string, expertise: string, email: string, phone: string, isEditorialBoardAuthor: boolean, isEditorInChief: boolean, isReviewerBoardMember: boolean, profilePictureUrl: string, profilePicture: ExternalBlob | null): Promise<void>;
    addNews(title: string, content: string, summary: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelSubscription(planId: string): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createFeaturedHomePageMagazine(title: string, issue: string, imageUrl: string, description: string, publishedDate: Time): Promise<void>;
    createHomePageArticle(title: string, author: string, description: string, submissionDate: Time): Promise<void>;
    createHomePageMagazine(title: string, issue: string, imageUrl: string, description: string, publishedDate: Time): Promise<void>;
    createMagazine(title: string, issue: string, imageUrl: string, description: string, publishedDate: Time): Promise<void>;
    createSubscription(planId: string, startDate: Time): Promise<void>;
    createUserReview(name: string, photoUrl: string | null, rating: bigint, feedback: string): Promise<void>;
    deleteArticle(articleTitle: string): Promise<void>;
    deleteEditorialMember(editorialMemberId: bigint): Promise<void>;
    deleteNews(newsId: string): Promise<void>;
    getAllArticlePreviews(): Promise<Array<ArticlePreview>>;
    getAllArticles(): Promise<Array<Article>>;
    getAllEditorialMembers(): Promise<Array<EditorialMember>>;
    getAllJournalsByYear(year: bigint): Promise<Array<Journal>>;
    getAllMagazines(): Promise<Array<Magazine>>;
    getAllNews(): Promise<Array<News>>;
    getAllPendingArticles(): Promise<Array<Article>>;
    getAllUserReviews(): Promise<Array<UserReview>>;
    getArticlePreview(id: bigint): Promise<ArticlePreview>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentJournal(): Promise<Journal | null>;
    getEditorInChiefMembers(): Promise<Array<EditorialMember>>;
    getEditorialBoardMembers(): Promise<Array<EditorialMember>>;
    getFilteredProfilesDTOs(isInstitute: boolean, isUnlimited: boolean): Promise<Array<ProfileOutput>>;
    getHomePageArticles(): Promise<Array<HomePageArticle>>;
    getHomePageMagazines(): Promise<Array<HomePageMagazine>>;
    getJournal(journalId: bigint): Promise<Journal>;
    getJournalCount(): Promise<bigint>;
    getLatestNews(count: bigint): Promise<Array<News>>;
    getMagazine(magazineId: bigint): Promise<Magazine>;
    getNews(newsId: string): Promise<News>;
    getNewsCount(): Promise<bigint>;
    getPendingArticleCount(): Promise<bigint>;
    getPlanCount(): Promise<bigint>;
    getRemainingArticles(user: Principal): Promise<bigint>;
    getReviewerBoardMembers(): Promise<Array<EditorialMember>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscriptionPlanObject(planId: string): Promise<SubscriptionPlan>;
    getSubscriptionPlans(): Promise<Array<SubscriptionPlan>>;
    getUserArticles(user: Principal): Promise<Array<Article>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserReview(userReviewId: bigint): Promise<UserReview>;
    getUsersByPlan(planId: string): Promise<Array<Principal>>;
    getVisitorCounter(): Promise<VisitorCounter>;
    hasActiveSubscription(user: Principal): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    saveCallerUserProfile(profile: ProfileInput): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitArticle(title: string, fileType: Variant_doc_pdf, fileName: string, fileSize: bigint, externalBlob: ExternalBlob): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateArticleStatus(user: Principal, articleTitle: string, newStatus: Variant_approved_rejected): Promise<void>;
    updateSubscriptionsTimestamp(): Promise<void>;
    updateVisitorCounter(pageViews: bigint, uniqueVisitors: bigint, totalSessions: bigint, averageSessionDuration: bigint, activeSessions: bigint | null): Promise<void>;
    uploadJournal(title: string, month: bigint, year: bigint, fileName: string, description: string, fileSize: bigint, externalBlob: ExternalBlob, isCurrent: boolean, isArchive: boolean): Promise<void>;
}
import type { Article as _Article, EditorialMember as _EditorialMember, ExternalBlob as _ExternalBlob, Journal as _Journal, ProfileOutput as _ProfileOutput, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, Time as _Time, UserProfile as _UserProfile, UserReview as _UserReview, UserRole as _UserRole, VisitorCounter as _VisitorCounter, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addEditorialMember(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: boolean, arg8: boolean, arg9: string, arg10: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEditorialMember(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEditorialMember(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, await to_candid_opt_n8(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async addNews(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNews(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNews(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelSubscription(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createFeaturedHomePageMagazine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFeaturedHomePageMagazine(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFeaturedHomePageMagazine(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createHomePageArticle(arg0: string, arg1: string, arg2: string, arg3: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHomePageArticle(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHomePageArticle(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createHomePageMagazine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHomePageMagazine(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHomePageMagazine(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createMagazine(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMagazine(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMagazine(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createSubscription(arg0: string, arg1: Time): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(arg0, arg1);
            return result;
        }
    }
    async createUserReview(arg0: string, arg1: string | null, arg2: bigint, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserReview(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserReview(arg0, to_candid_opt_n12(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async deleteArticle(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteArticle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteArticle(arg0);
            return result;
        }
    }
    async deleteEditorialMember(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEditorialMember(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEditorialMember(arg0);
            return result;
        }
    }
    async deleteNews(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async getAllArticlePreviews(): Promise<Array<ArticlePreview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticlePreviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticlePreviews();
            return result;
        }
    }
    async getAllArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllArticles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllArticles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEditorialMembers(): Promise<Array<EditorialMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEditorialMembers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEditorialMembers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJournalsByYear(arg0: bigint): Promise<Array<Journal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJournalsByYear(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJournalsByYear(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMagazines(): Promise<Array<Magazine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMagazines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMagazines();
            return result;
        }
    }
    async getAllNews(): Promise<Array<News>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return result;
        }
    }
    async getAllPendingArticles(): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingArticles();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingArticles();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserReviews(): Promise<Array<UserReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserReviews();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserReviews();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArticlePreview(arg0: bigint): Promise<ArticlePreview> {
        if (this.processError) {
            try {
                const result = await this.actor.getArticlePreview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArticlePreview(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentJournal(): Promise<Journal | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentJournal();
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentJournal();
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEditorInChiefMembers(): Promise<Array<EditorialMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEditorInChiefMembers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEditorInChiefMembers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEditorialBoardMembers(): Promise<Array<EditorialMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEditorialBoardMembers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEditorialBoardMembers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFilteredProfilesDTOs(arg0: boolean, arg1: boolean): Promise<Array<ProfileOutput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFilteredProfilesDTOs(arg0, arg1);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFilteredProfilesDTOs(arg0, arg1);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomePageArticles(): Promise<Array<HomePageArticle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomePageArticles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomePageArticles();
            return result;
        }
    }
    async getHomePageMagazines(): Promise<Array<HomePageMagazine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomePageMagazines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomePageMagazines();
            return result;
        }
    }
    async getJournal(arg0: bigint): Promise<Journal> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournal(arg0);
                return from_candid_Journal_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournal(arg0);
            return from_candid_Journal_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJournalCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalCount();
            return result;
        }
    }
    async getLatestNews(arg0: bigint): Promise<Array<News>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestNews(arg0);
            return result;
        }
    }
    async getMagazine(arg0: bigint): Promise<Magazine> {
        if (this.processError) {
            try {
                const result = await this.actor.getMagazine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMagazine(arg0);
            return result;
        }
    }
    async getNews(arg0: string): Promise<News> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews(arg0);
            return result;
        }
    }
    async getNewsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsCount();
            return result;
        }
    }
    async getPendingArticleCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingArticleCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingArticleCount();
            return result;
        }
    }
    async getPlanCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlanCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlanCount();
            return result;
        }
    }
    async getRemainingArticles(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingArticles(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingArticles(arg0);
            return result;
        }
    }
    async getReviewerBoardMembers(): Promise<Array<EditorialMember>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewerBoardMembers();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewerBoardMembers();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscriptionPlanObject(arg0: string): Promise<SubscriptionPlan> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionPlanObject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionPlanObject(arg0);
            return result;
        }
    }
    async getSubscriptionPlans(): Promise<Array<SubscriptionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionPlans();
            return result;
        }
    }
    async getUserArticles(arg0: Principal): Promise<Array<Article>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserArticles(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserArticles(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserReview(arg0: bigint): Promise<UserReview> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserReview(arg0);
                return from_candid_UserReview_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserReview(arg0);
            return from_candid_UserReview_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersByPlan(arg0: string): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersByPlan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersByPlan(arg0);
            return result;
        }
    }
    async getVisitorCounter(): Promise<VisitorCounter> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisitorCounter();
                return from_candid_VisitorCounter_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisitorCounter();
            return from_candid_VisitorCounter_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasActiveSubscription(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasActiveSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasActiveSubscription(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: ProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitArticle(arg0: string, arg1: Variant_doc_pdf, arg2: string, arg3: bigint, arg4: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitArticle(arg0, to_candid_variant_n44(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitArticle(arg0, to_candid_variant_n44(this._uploadFile, this._downloadFile, arg1), arg2, arg3, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateArticleStatus(arg0: Principal, arg1: string, arg2: Variant_approved_rejected): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateArticleStatus(arg0, arg1, to_candid_variant_n45(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateArticleStatus(arg0, arg1, to_candid_variant_n45(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateSubscriptionsTimestamp(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionsTimestamp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionsTimestamp();
            return result;
        }
    }
    async updateVisitorCounter(arg0: bigint, arg1: bigint, arg2: bigint, arg3: bigint, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisitorCounter(arg0, arg1, arg2, arg3, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisitorCounter(arg0, arg1, arg2, arg3, to_candid_opt_n46(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async uploadJournal(arg0: string, arg1: bigint, arg2: bigint, arg3: string, arg4: string, arg5: bigint, arg6: ExternalBlob, arg7: boolean, arg8: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadJournal(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadJournal(arg0, arg1, arg2, arg3, arg4, arg5, await to_candid_ExternalBlob_n9(this._uploadFile, this._downloadFile, arg6), arg7, arg8);
            return result;
        }
    }
}
async function from_candid_Article_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Article): Promise<Article> {
    return await from_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function from_candid_EditorialMember_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EditorialMember): Promise<EditorialMember> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_Journal_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Journal): Promise<Journal> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileOutput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileOutput): ProfileOutput {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserReview_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserReview): UserReview {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_VisitorCounter_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisitorCounter): VisitorCounter {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Journal]): Promise<Journal | null> {
    return value.length === 0 ? null : await from_candid_Journal_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Subscription>]): Array<Subscription> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        pending: null;
    } | {
        approved: null;
    } | {
        rejected: null;
    };
    title: string;
    externalBlob: _ExternalBlob;
    fileName: string;
    filePath: string;
    fileSize: bigint;
    fileType: {
        doc: null;
    } | {
        pdf: null;
    };
    author: string;
    submissionDate: _Time;
}): Promise<{
    status: Variant_pending_approved_rejected;
    title: string;
    externalBlob: ExternalBlob;
    fileName: string;
    filePath: string;
    fileSize: bigint;
    fileType: Variant_doc_pdf;
    author: string;
    submissionDate: Time;
}> {
    return {
        status: from_candid_variant_n16(_uploadFile, _downloadFile, value.status),
        title: value.title,
        externalBlob: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.externalBlob),
        fileName: value.fileName,
        filePath: value.filePath,
        fileSize: value.fileSize,
        fileType: from_candid_variant_n18(_uploadFile, _downloadFile, value.fileType),
        author: value.author,
        submissionDate: value.submissionDate
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    blob: [] | [_ExternalBlob];
    name: string;
    createdAt: _Time;
    role: string;
    isEditorialBoardAuthor: boolean;
    email: string;
    expertise: string;
    profilePictureUrl: string;
    isEditorInChief: boolean;
    phone: string;
    isReviewerBoardMember: boolean;
    qualification: string;
}): Promise<{
    id: bigint;
    blob?: ExternalBlob;
    name: string;
    createdAt: Time;
    role: string;
    isEditorialBoardAuthor: boolean;
    email: string;
    expertise: string;
    profilePictureUrl: string;
    isEditorInChief: boolean;
    phone: string;
    isReviewerBoardMember: boolean;
    qualification: string;
}> {
    return {
        id: value.id,
        blob: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.blob)),
        name: value.name,
        createdAt: value.createdAt,
        role: value.role,
        isEditorialBoardAuthor: value.isEditorialBoardAuthor,
        email: value.email,
        expertise: value.expertise,
        profilePictureUrl: value.profilePictureUrl,
        isEditorInChief: value.isEditorInChief,
        phone: value.phone,
        isReviewerBoardMember: value.isReviewerBoardMember,
        qualification: value.qualification
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    month: bigint;
    title: string;
    blob: _ExternalBlob;
    year: bigint;
    description: string;
    fileSize: bigint;
    fileType: {
        pdf: null;
    };
    filename: string;
    isArchive: boolean;
    isCurrent: boolean;
    uploadDate: _Time;
}): Promise<{
    id: bigint;
    month: bigint;
    title: string;
    blob: ExternalBlob;
    year: bigint;
    description: string;
    fileSize: bigint;
    fileType: Variant_pdf;
    filename: string;
    isArchive: boolean;
    isCurrent: boolean;
    uploadDate: Time;
}> {
    return {
        id: value.id,
        month: value.month,
        title: value.title,
        blob: await from_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.blob),
        year: value.year,
        description: value.description,
        fileSize: value.fileSize,
        fileType: from_candid_variant_n26(_uploadFile, _downloadFile, value.fileType),
        filename: value.filename,
        isArchive: value.isArchive,
        isCurrent: value.isCurrent,
        uploadDate: value.uploadDate
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    photoUrl: [] | [string];
    feedback: string;
    rating: bigint;
}): {
    id: bigint;
    name: string;
    photoUrl?: string;
    feedback: string;
    rating: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        photoUrl: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.photoUrl)),
        feedback: value.feedback,
        rating: value.rating
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    occupation: string;
    name: string;
    isUnlimited: boolean;
    email: string;
    phone: string;
    isInstitute: boolean;
    activeSubscriptions: [] | [Array<_Subscription>];
    qualification: string;
}): {
    occupation: string;
    name: string;
    isUnlimited: boolean;
    email: string;
    phone: string;
    isInstitute: boolean;
    activeSubscriptions?: Array<Subscription>;
    qualification: string;
} {
    return {
        occupation: value.occupation,
        name: value.name,
        isUnlimited: value.isUnlimited,
        email: value.email,
        phone: value.phone,
        isInstitute: value.isInstitute,
        activeSubscriptions: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.activeSubscriptions)),
        qualification: value.qualification
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    averageSessionDuration: bigint;
    activeSessions: [] | [bigint];
    totalSessions: bigint;
    pageViews: bigint;
    uniqueVisitors: bigint;
}): {
    averageSessionDuration: bigint;
    activeSessions?: bigint;
    totalSessions: bigint;
    pageViews: bigint;
    uniqueVisitors: bigint;
} {
    return {
        averageSessionDuration: value.averageSessionDuration,
        activeSessions: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.activeSessions)),
        totalSessions: value.totalSessions,
        pageViews: value.pageViews,
        uniqueVisitors: value.uniqueVisitors
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Variant_pending_approved_rejected {
    return "pending" in value ? Variant_pending_approved_rejected.pending : "approved" in value ? Variant_pending_approved_rejected.approved : "rejected" in value ? Variant_pending_approved_rejected.rejected : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    doc: null;
} | {
    pdf: null;
}): Variant_doc_pdf {
    return "doc" in value ? Variant_doc_pdf.doc : "pdf" in value ? Variant_doc_pdf.pdf : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
}): Variant_pdf {
    return "pdf" in value ? Variant_pdf.pdf : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n41(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
async function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Article>): Promise<Array<Article>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Article_n14(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EditorialMember>): Promise<Array<EditorialMember>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EditorialMember_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Journal>): Promise<Array<Journal>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Journal_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserReview>): Array<UserReview> {
    return value.map((x)=>from_candid_UserReview_n28(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProfileOutput>): Array<ProfileOutput> {
    return value.map((x)=>from_candid_ProfileOutput_n36(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n9(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_doc_pdf): {
    doc: null;
} | {
    pdf: null;
} {
    return value == Variant_doc_pdf.doc ? {
        doc: null
    } : value == Variant_doc_pdf.pdf ? {
        pdf: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_approved_rejected): {
    approved: null;
} | {
    rejected: null;
} {
    return value == Variant_approved_rejected.approved ? {
        approved: null
    } : value == Variant_approved_rejected.rejected ? {
        rejected: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
